### ISSUE TITLE
Issue01 - Workshop Stat

### ISSUE THREAD

**Issue by yongcheoljeong** [SqixOW/NYXL_WorkshopLogger#1]
- workshopstat (0차 스탯) 추가사항
`Time Played`
`is_alive: bool`
`is_crouching: bool`

- PlayerData 중 ResourceData 복제
`Cooldown1`, `Cooldown2`, `UltimateCharge`, `UltimatesEarned`, `UltimatesUsed`, `Point`, `MaxHealth`, `Position`

**Comment by SqixOW** [comment]
#Issue01에 대한 Handling number 01 commit
- workshopstat (0차 스탯) 추가사항 (워크샵 코드 6P106)
`Time Played -> Time Played에 대한 Action 항목이 미존재 => 프로그램 메모리 활용한 루틴 제작 필요` 
`is_alive: bool -> 해결 완료`
`is_crouching: bool -> 해결 완료`

- PlayerData 중 ResourceData 복제
`Cooldown1`, `Cooldown2`, `UltimateCharge`, `UltimatesEarned`, `UltimatesUsed`, `Point`, `MaxHealth`, `Position`
`-> 해당 데이터에 대한 Datastruct 구성 완료, 핸들러 작성을 통해 CSV 생성하는 루틴 작성 필요`

**Comment by SqixOW** [comment]
#Issue01에 대한 Handling number 02 commit
- PlayerData 중 ResourceData 복제
`-> 해당 데이터에 대한 CSV 생성 루틴 작성 완료`

**Comment by SqixOW** [comment]
Time Played에 대한 코드 생성(imt)으로 해당 issue는 Close 하겠습니다.

**Comment by SqixOW** [comment]
Time Played에 대한 코드 생성(imt)으로 해당 issue는 Close 하겠습니다.
