### ISSUE TITLE
Issue03 - Stat 추가

### ISSUE THREAD

**Issue by yongcheoljeong** [SqixOW/NYXL_WorkshopLogger#3]
1. `Health` 추가 (워크샵 value 중 'HEALTH' 사용)
2. `DefensiveAssists` 추가
3. `OffensiveAssists` 추가
4. `HasStatus` 추가 
return: str = 'hacked' or 'burning' or 'knocked down' or 'asleep' or 'frozen' or 'unkillable' or 'invincible' or 'phased out' or 'rooted' or 'stunned'

**Comment by SqixOW** [comment]
#Issue03 - Handling 01을 통한 issue handling 완료. confirm 이후 close 예정

**Comment by yongcheoljeong** [comment]
모두 추가됨
