### ISSUE TITLE
Issue 04 - `Section` 수정

### ISSUE THREAD

**Issue by yongcheoljeong** [SqixOW/NYXL_WorkshopLogger#4]
현재 쟁탈 제외한 맵에서 라운드가 바뀌어도 '0'으로 찍히는 것을 라운드 변경 시마다 'Section' += 1 해주는 것으로 변경 필요

**Comment by SqixOW** [comment]
Issue 04 - Section 수정에 대한 커밋(Handling - 01)을 통해 해결 완료. 확인 후 Issue Close 바랍니다.

**Comment by yongcheoljeong** [comment]
1. 쟁탈맵들에서 round에 따라 section 번호가 올라가지 않는 문제
2. 쟁탈맵들에서 section 순서에 따라 timestamp가 찍히지 않는 문제

**Comment by SqixOW** [comment]
Issue 04 - Handling 02
1. Round에 따른 Section 번호 : 부산 맵 순서의 문제로 해결 완료
2. 쟁탈맵에 대한 예외처리 완료.

**Comment by yongcheoljeong** [comment]
완료
