### ISSUE TITLE
Issue 06 - HealingReceived 안 찍히는 문제

### ISSUE THREAD

**Issue by yongcheoljeong** [SqixOW/NYXL_WorkshopLogger#6]
워크샵 스탯 중 HealingReceived 모든 스탯이 0으로 나옴.
워크샵 알고리즘 상 문제인 듯.

**Comment by SqixOW** [comment]
Workshop Code 중 해당 스탯을 찍는 코드가

Player Hero Stat(Event Player, All Heroes, Healing Received)

로 잡혀있음.

해당 블럭을 

Player Hero Stat(Event Player, Hero Of, Event Player, Healing Received)

로 파라미터 변경 후 테스트 예정.

**Comment by yongcheoljeong** [comment]
이제 HealingReceived가 찍히긴 하는데
팀 전체의 HealingDealt 와 HealingReceived 가 일치하지 않는 문제. 원래 그럴 수 있나?
그리고 HealingReceived가 음수가 찍히는 경우가 있는데 왜지?

**Comment by yongcheoljeong** [comment]
이유 알 것 같다.
현재 workshop 스탯이 찍히는건 Event Player의 All Heroes 이기 때문에 Player 기준으로 dx 를 구해주는데 Healing Received만 Hero of Event Player 로 집계돼서 영웅마다 HealingReceived가 0으로 reset되기 때문에 생기는 문제인 듯.
All Heroes로 집계가 안되는 문제인거면 HealingReceived만 따로 분류해서 핸들링 해야할듯?

**Comment by yongcheoljeong** [comment]
TraditionalStat 레벨에서 Player 기준으로 누적시켜주는 방식으로 해결.
